'use client';

import { IconArchive, IconArchiveOff } from '@tabler/icons-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { CreateFormsWrapper } from '@/components/create-forms-wrapper';
import { CategoryCards } from '@/components/feature/category/category-cards';
import { CategoryForm } from '@/components/feature/category/category-form';
import { SimpleCategoryTree } from '@/components/feature/category/simple-category-tree';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useSidebar } from '@/components/ui/sidebar';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { trpc } from '@/lib/trpc';
import type { CategoryFromTRPC } from '@/types/trpc';

export default function CategoriesPage() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<CategoryFromTRPC | null>(null);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [categoryToDelete, setCategoryToDelete] = useState<CategoryFromTRPC | null>(null);
  const [activeTab, setActiveTab] = useState<'expense' | 'income'>('expense');
  const [showArchived, setShowArchived] = useState(false);
  const { isMobile } = useSidebar();

  const { data: categoriesData, isLoading: categoriesLoading } = trpc.categories.getAll.useQuery({
    includeArchived: true,
  });
  const utils = trpc.useUtils();


  const expenseCategories = categoriesData?.filter((cat) => {
    const isExpense = cat.flow === 'expense';
    const isArchived = cat.isArchived === true;
    const shouldShow = showArchived ? isArchived : !isArchived;
    return isExpense && shouldShow;
  }) || [];

  const incomeCategories = categoriesData?.filter((cat) => {
    const isIncome = cat.flow === 'income';
    const isArchived = cat.isArchived === true;
    const shouldShow = showArchived ? isArchived : !isArchived;
    return isIncome && shouldShow;
  }) || [];

  // Count archived categories
  const archivedExpenseCount = categoriesData?.filter((cat) =>
    cat.flow === 'expense' && cat.isArchived
  ).length || 0;
  const archivedIncomeCount = categoriesData?.filter((cat) =>
    cat.flow === 'income' && cat.isArchived
  ).length || 0;
  const totalArchivedCount = archivedExpenseCount + archivedIncomeCount;


  const createCategory = trpc.categories.create.useMutation({
    onSuccess: () => {
      toast.success('Category created successfully!');
      utils.categories.getAll.invalidate();
      setIsDrawerOpen(false);
      setEditingCategory(null);
    },
    onError: (error) => toast.error(`Error creating category: ${error.message}`),
  });

  const updateCategory = trpc.categories.update.useMutation({
    onSuccess: () => {
      toast.success('Category updated successfully!');
      utils.categories.getAll.invalidate();
      setIsDrawerOpen(false);
      setEditingCategory(null);
    },
    onError: (error) => toast.error(`Error updating category: ${error.message}`),
  });

  const deleteCategory = trpc.categories.archive.useMutation({
    onSuccess: () => {
      toast.success('Category deleted successfully!');
      utils.categories.getAll.invalidate();
      setDeleteDialogOpen(false);
      setCategoryToDelete(null);
    },
    onError: (error) => toast.error(`Error deleting category: ${error.message}`),
  });

  const unarchiveCategory = trpc.categories.unarchive.useMutation({
    onSuccess: () => {
      toast.success('Category restored successfully!');
      utils.categories.getAll.invalidate();
    },
    onError: (error) => toast.error(`Error restoring category: ${error.message}`),
  });

  const getParentCategoryName = (parentId: string | null | undefined) => {
    if (!parentId || !categoriesData) return null;
    const parent = categoriesData.find((cat) => cat.id === parentId);
    return parent?.name || null;
  };


  const handleCreateSubcategory = (parentCategory: CategoryFromTRPC) => {
    // Create a new category object with the parent's ID as parentId
    const newCategory: Partial<CategoryFromTRPC> = {
      id: undefined, // Will be generated by the server
      name: '',
      flow: parentCategory.flow, // Inherit flow from parent
      parentId: parentCategory.id,
      isArchived: false,
      userId: '',
      createdAt: '',
      archivedAt: null,
    };
    setEditingCategory(newCategory as CategoryFromTRPC);
    setIsDrawerOpen(true);
  };

  const handleEditCategory = (category: CategoryFromTRPC) => {
    setEditingCategory(category);
    setIsDrawerOpen(true);
  };

  const handleViewCategory = (category: CategoryFromTRPC) => {
    setEditingCategory(category);
    setIsDrawerOpen(true);
  };

  const handleDeleteCategory = (category: CategoryFromTRPC) => {
    setCategoryToDelete(category);
    setDeleteDialogOpen(true);
  };

  const handleUnarchiveCategory = async (category: CategoryFromTRPC) => {
    await unarchiveCategory.mutateAsync({ id: category.id });
  };

  const confirmDeleteCategory = async () => {
    if (categoryToDelete)
      await deleteCategory.mutateAsync({ id: categoryToDelete.id, cascade: true });
  };

  const handleFormSubmit = async (data: {
    name: string;
    flow: 'expense' | 'income';
    parentId?: string;
  }) => {
    if (editingCategory?.id) {
      await updateCategory.mutateAsync({
        id: editingCategory.id,
        name: data.name,
        flow: data.flow,
        parentId: data.parentId || null,
      });
    } else {
      await createCategory.mutateAsync({
        name: data.name,
        flow: data.flow,
        parentId: data.parentId,
      });
    }
  };

  const handleDrawerClose = () => {
    setIsDrawerOpen(false);
    setEditingCategory(null);
  };

  return (
    <>
      <div className="flex flex-1 flex-col">
        <div className="@container/main flex flex-1 flex-col gap-2">
          <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
            <CategoryCards />
            <div className="px-4 lg:px-6">
              <Card>
                <CardHeader>
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <CardTitle>Category management</CardTitle>
                      <CardDescription>
                        Here you can manage your categories
                        {totalArchivedCount > 0 && (
                          <span className="ml-2 text-sm text-muted-foreground">
                            ({totalArchivedCount} archived)
                          </span>
                        )}
                      </CardDescription>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button
                        variant={showArchived ? "default" : "outline"}
                        size="sm"
                        onClick={() => setShowArchived(!showArchived)}
                        disabled={totalArchivedCount === 0 && !showArchived}
                      >
                        {showArchived ? (
                          <>
                            <IconArchiveOff className="mr-2 h-4 w-4" />
                            Show Active
                          </>
                        ) : (
                          <>
                            <IconArchive className="mr-2 h-4 w-4" />
                            Show Archived ({totalArchivedCount})
                          </>
                        )}
                      </Button>
                      <CreateFormsWrapper
                        context="category"
                        onSuccess={() => {
                          utils.categories.getAll.invalidate();
                        }}
                      />
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  {categoriesLoading ? (
                    <div className="text-center py-8">
                      <div className="text-lg">Loading categories...</div>
                    </div>
                  ) : (
                    <Tabs
                      value={activeTab}
                      onValueChange={(value) => setActiveTab(value as 'expense' | 'income')}
                    >
                      <TabsList className="">
                        <TabsTrigger value="expense">Expense</TabsTrigger>
                        <TabsTrigger value="income">Income</TabsTrigger>
                      </TabsList>

                      <TabsContent value="expense" className="mt-4">
                        {(() => {
                          console.log('Rendering expense tab - showArchived:', showArchived);
                          console.log('Rendering expense tab - expenseCategories:', expenseCategories);
                          console.log('Rendering expense tab - expenseCategories.length:', expenseCategories.length);
                          return null;
                        })()}
                        {expenseCategories.length > 0 ? (
                          <SimpleCategoryTree
                            data={expenseCategories}
                            onView={handleViewCategory}
                            onEdit={handleEditCategory}
                            onDelete={handleDeleteCategory}
                            onUnarchive={handleUnarchiveCategory}
                            onCreateSubcategory={handleCreateSubcategory}
                            getParentCategoryName={getParentCategoryName}
                          />
                        ) : (
                          <div className="text-center py-8 text-muted-foreground">
                            <div className="text-lg">
                              {showArchived ? 'No archived expense categories found' : 'No expense categories found'}
                            </div>
                            <div className="text-sm">
                              {showArchived
                                ? 'No expense categories have been archived yet'
                                : 'Create your first expense category to start organizing your expenses'
                              }
                            </div>
                          </div>
                        )}
                      </TabsContent>

                      <TabsContent value="income" className="mt-4">
                        {incomeCategories.length > 0 ? (
                          <SimpleCategoryTree
                            data={incomeCategories}
                            onView={handleViewCategory}
                            onEdit={handleEditCategory}
                            onDelete={handleDeleteCategory}
                            onUnarchive={handleUnarchiveCategory}
                            onCreateSubcategory={handleCreateSubcategory}
                            getParentCategoryName={getParentCategoryName}
                          />
                        ) : (
                          <div className="text-center py-8 text-muted-foreground">
                            <div className="text-lg">
                              {showArchived ? 'No archived income categories found' : 'No income categories found'}
                            </div>
                            <div className="text-sm">
                              {showArchived
                                ? 'No income categories have been archived yet'
                                : 'Create your first income category to start organizing your incomes'
                              }
                            </div>
                          </div>
                        )}
                      </TabsContent>
                    </Tabs>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>

      {categoriesData && (
        <CategoryForm
          category={editingCategory || undefined}
          onSubmit={handleFormSubmit}
          onCancel={handleDrawerClose}
          isLoading={createCategory.isPending || updateCategory.isPending}
          open={isDrawerOpen}
          onOpenChange={setIsDrawerOpen}
          direction={isMobile ? 'bottom' : 'right'}
          defaultFlow={activeTab}
        />
      )}

      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Confirm deletion</AlertDialogTitle>
            <AlertDialogDescription>
              {categoryToDelete?.isArchived ? (
                <>
                  Are you sure you want to permanently delete the category &quot;{categoryToDelete?.name}&quot;?
                  This action cannot be undone.
                </>
              ) : (
                <>
                  Are you sure you want to archive the category &quot;{categoryToDelete?.name}&quot;?
                  This will also archive all its subcategories.
                  <br />
                  <br />
                  <strong>Type:</strong> {categoryToDelete?.flow}
                </>
              )}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDeleteCategory}
              className="bg-destructive text-white hover:bg-destructive/90"
              disabled={deleteCategory.isPending}
            >
              {deleteCategory.isPending ? 'Processing...' : categoryToDelete?.isArchived ? 'Permanently Delete' : 'Archive'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
